title: Empty Words
author: Ladios SatÅ
email: ladiossato@gmail.com
description: >-
  Movement inside the mind that most people never see.
  Patterns before thought. Inner machinery shaping choices.

baseurl: "/emptywords"
url: "https://empty-words.com"

markdown: kramdown
permalink: /writings/:title/

collections:
  writings:
    output: true
    permalink: /writings/:title/

defaults:
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "writing"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
